// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVlaPEDuxoxu-xzSPiAyQz5ffn9eHJMhs',
    appId: '1:855310351966:web:45e54d01473b824ac93ecf',
    messagingSenderId: '855310351966',
    projectId: 'retide-6fb42',
    authDomain: 'retide-6fb42.firebaseapp.com',
    storageBucket: 'retide-6fb42.firebasestorage.app',
    measurementId: 'G-WKNJQS57BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjfekYDYLQ11asqtkrBw0aQljPQlFbA7o',
    appId: '1:855310351966:android:364f56a98781e53cc93ecf',
    messagingSenderId: '855310351966',
    projectId: 'retide-6fb42',
    storageBucket: 'retide-6fb42.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVlaPEDuxoxu-xzSPiAyQz5ffn9eHJMhs',
    appId: '1:855310351966:web:b884dab1b369f422c93ecf',
    messagingSenderId: '855310351966',
    projectId: 'retide-6fb42',
    authDomain: 'retide-6fb42.firebaseapp.com',
    storageBucket: 'retide-6fb42.firebasestorage.app',
    measurementId: 'G-N8P6TCM1XZ',
  );
}
